### ISSUE TITLE
Can't get it compiled on Windows 7 and Matlab2014a

### ISSUE THREAD

**Issue by t4qjXH8N** [HBadertscher/Matlab_BaslerCamDriver#7] opened 2015-06-18 13:29 UTC
Hi folks,

I can't get the Basler driver compiled on my system. Please help!
This is what I have done so far: I have downloaded Boost 1.55.0 and Pylon 4.2 . Since boost does not compile on my system (don't know why), I downloaded the precompiled binaries and supposed that the binaries are in the folder "lib64-msvc-10.0" (there is no folder stage/libs in my Boost folder). Hence I changed in the make script the line with "stage/libs" to "lib64-msvc-10.0". No effect.  The linker paths to the pylon stuff are correct. Any ideas?

Here is the Matlab output:
```
>> make
=> Creating Libraries
Building with 'Microsoft Windows SDK 7.1 (C++)'.
MEX completed successfully.
Building with 'Microsoft Windows SDK 7.1 (C++)'.
MEX completed successfully.
=> Creating Functions
Building with 'Microsoft Windows SDK 7.1 (C++)'.
MEX completed successfully.
Building with 'Microsoft Windows SDK 7.1 (C++)'.
MEX completed successfully.
Building with 'Microsoft Windows SDK 7.1 (C++)'.
Error using mex
baslerGetParameter.cpp
D:\Mitarbeiter\Christian\HBadertscher-Matlab_BaslerCamDriver-419332a\baslerGetParameter.cpp(13)
: error C2332: 'enum' : missing tag name
D:\Mitarbeiter\Christian\HBadertscher-Matlab_BaslerCamDriver-419332a\baslerGetParameter.cpp(13)
: error C2236: unexpected 'class' 'ParamType'. Did you forget a ';'?
D:\Mitarbeiter\Christian\HBadertscher-Matlab_BaslerCamDriver-419332a\baslerGetParameter.cpp(13)
: error C3381: 'ParamType' : assembly access specifiers are only
available in code compiled with a /clr option
D:\Mitarbeiter\Christian\HBadertscher-Matlab_BaslerCamDriver-419332a\baslerGetParameter.cpp(14)
: error C4430: missing type specifier - int assumed. Note: C++ does
not support default-int
D:\Mitarbeiter\Christian\HBadertscher-Matlab_BaslerCamDriver-419332a\baslerGetParameter.cpp(15)
: error C4430: missing type specifier - int assumed. Note: C++ does
not support default-int
D:\Mitarbeiter\Christian\HBadertscher-Matlab_BaslerCamDriver-419332a\baslerGetParameter.cpp(16)
: error C4430: missing type specifier - int assumed. Note: C++ does
not support default-int
D:\Mitarbeiter\Christian\HBadertscher-Matlab_BaslerCamDriver-419332a\baslerGetParameter.cpp(18)
: error C2143: syntax error : missing ';' before '}'
D:\Mitarbeiter\Christian\HBadertscher-Matlab_BaslerCamDriver-419332a\baslerGetParameter.cpp(18)
: error C4430: missing type specifier - int assumed. Note: C++ does
not support default-int
D:\Mitarbeiter\Christian\HBadertscher-Matlab_BaslerCamDriver-419332a\baslerGetParameter.cpp(40)
: error C2039: 'Float' : is not a member of 'ParamType'
        D:\Mitarbeiter\Christian\HBadertscher-Matlab_BaslerCamDriver-419332a\baslerGetParameter.cpp(13)
        : see declaration of 'ParamType'
D:\Mitarbeiter\Christian\HBadertscher-Matlab_BaslerCamDriver-419332a\baslerGetParameter.cpp(40)
: error C2065: 'Float' : undeclared identifier
D:\Mitarbeiter\Christian\HBadertscher-Matlab_BaslerCamDriver-419332a\baslerGetParameter.cpp(41)
: error C2039: 'Int' : is not a member of 'ParamType'
        D:\Mitarbeiter\Christian\HBadertscher-Matlab_BaslerCamDriver-419332a\baslerGetParameter.cpp(13)
        : see declaration of 'ParamType'
D:\Mitarbeiter\Christian\HBadertscher-Matlab_BaslerCamDriver-419332a\baslerGetParameter.cpp(41)
: error C2065: 'Int' : undeclared identifier
D:\Mitarbeiter\Christian\HBadertscher-Matlab_BaslerCamDriver-419332a\baslerGetParameter.cpp(42)
: error C2039: 'Bool' : is not a member of 'ParamType'
        D:\Mitarbeiter\Christian\HBadertscher-Matlab_BaslerCamDriver-419332a\baslerGetParameter.cpp(13)
        : see declaration of 'ParamType'
D:\Mitarbeiter\Christian\HBadertscher-Matlab_BaslerCamDriver-419332a\baslerGetParameter.cpp(42)
: error C2065: 'Bool' : undeclared identifier
D:\Mitarbeiter\Christian\HBadertscher-Matlab_BaslerCamDriver-419332a\baslerGetParameter.cpp(43)
: error C2039: 'String' : is not a member of 'ParamType'
        D:\Mitarbeiter\Christian\HBadertscher-Matlab_BaslerCamDriver-419332a\baslerGetParameter.cpp(13)
        : see declaration of 'ParamType'
D:\Mitarbeiter\Christian\HBadertscher-Matlab_BaslerCamDriver-419332a\baslerGetParameter.cpp(43)
: error C2065: 'String' : undeclared identifier
D:\Mitarbeiter\Christian\HBadertscher-Matlab_BaslerCamDriver-419332a\baslerGetParameter.cpp(86)
: error C2450: switch expression of type 'ParamType' is illegal
        No user-defined-conversion operator available that can perform
        this conversion, or the operator cannot be called
D:\Mitarbeiter\Christian\HBadertscher-Matlab_BaslerCamDriver-419332a\baslerGetParameter.cpp(88)
: error C2039: 'Float' : is not a member of 'ParamType'
        D:\Mitarbeiter\Christian\HBadertscher-Matlab_BaslerCamDriver-419332a\baslerGetParameter.cpp(13)
        : see declaration of 'ParamType'


D:\Mitarbeiter\Christian\HBadertscher-Matlab_BaslerCamDriver-419332a\baslerGetParameter.cpp(88)
: error C2065: 'Float' : undeclared identifier

D:\Mitarbeiter\Christian\HBadertscher-Matlab_BaslerCamDriver-419332a\baslerGetParameter.cpp(88)
: error C2051: case expression not constant
D:\Mitarbeiter\Christian\HBadertscher-Matlab_BaslerCamDriver-419332a\baslerGetParameter.cpp(95)
: error C2039: 'Int' : is not a member of 'ParamType'
        D:\Mitarbeiter\Christian\HBadertscher-Matlab_BaslerCamDriver-419332a\baslerGetParameter.cpp(13)
        : see declaration of 'ParamType'
D:\Mitarbeiter\Christian\HBadertscher-Matlab_BaslerCamDriver-419332a\baslerGetParameter.cpp(95)
: error C2065: 'Int' : undeclared identifier
D:\Mitarbeiter\Christian\HBadertscher-Matlab_BaslerCamDriver-419332a\baslerGetParameter.cpp(95)
: error C2051: case expression not constant
D:\Mitarbeiter\Christian\HBadertscher-Matlab_BaslerCamDriver-419332a\baslerGetParameter.cpp(104)
: error C2039: 'Bool' : is not a member of 'ParamType'
        D:\Mitarbeiter\Christian\HBadertscher-Matlab_BaslerCamDriver-419332a\baslerGetParameter.cpp(13)
        : see declaration of 'ParamType'
D:\Mitarbeiter\Christian\HBadertscher-Matlab_BaslerCamDriver-419332a\baslerGetParameter.cpp(104)
: error C2065: 'Bool' : undeclared identifier
D:\Mitarbeiter\Christian\HBadertscher-Matlab_BaslerCamDriver-419332a\baslerGetParameter.cpp(104)
: error C2051: case expression not constant
D:\Mitarbeiter\Christian\HBadertscher-Matlab_BaslerCamDriver-419332a\baslerGetParameter.cpp(111)
: error C2039: 'String' : is not a member of 'ParamType'
        D:\Mitarbeiter\Christian\HBadertscher-Matlab_BaslerCamDriver-419332a\baslerGetParameter.cpp(13)
        : see declaration of 'ParamType'
D:\Mitarbeiter\Christian\HBadertscher-Matlab_BaslerCamDriver-419332a\baslerGetParameter.cpp(111)
: error C2065: 'String' : undeclared identifier
D:\Mitarbeiter\Christian\HBadertscher-Matlab_BaslerCamDriver-419332a\baslerGetParameter.cpp(111)
: error C2051: case expression not constant
D:\Mitarbeiter\Christian\HBadertscher-Matlab_BaslerCamDriver-419332a\baslerGetParameter.cpp(124)
: warning C4065: switch statement contains 'default' but no 'case'
labels



Error in make (line 63)
            mex(flags{:},ipaths,lpaths,libraryObjects{:},drivers{k})
 
>>
```

**Comment by HBadertscher** [comment] 2015-06-20 08:26
Hi, thank you for the bug report. I'll try to reproduce the error and get back to you asap.

**Comment by smwasser** [comment] 2015-07-23 18:15
Hi - I've just come across the same error and was wondering if there were any updates yet to resolving it? Also, did you use 32 or 64bit Matlab and does it matter? Thank you.

**Comment by HBadertscher** [comment] 2015-07-29 07:40
Sorry for the delay. Now, from the posted log I assume that you are using the Microsoft Windows SDK 7.1, which is recommended by MATLAB. Is this correct? This would lead to the following problem: SDK 7.1 includes the Visual Studio 2010 compilers, which are quite old by now. The BaslerCamDriver however relies on the C++11 standard, which is not available in SDK 7.1. Could you install and use [Microsoft Visual Studio](http://www.visualstudio.com/)? Visual Studio Community is available free of charge for non-commercial applications. With that the compilation should work fine, as from the error message I don't think this problem is related to Boost.

About 32bit / 64bit: I am using a 64bit version of MATLAB and use the 64-bit Boost and Pylon libraries. With 32bit MATLAB you will need to use the 32bit libraries, so please change according library paths. I am hoping to create a more intelligent build script which would detect the paths automatically, but this is will take some more time.

**Comment by smwasser** [comment] 2015-07-31 17:23
Thank you very much for your help! Using the 2013 SDK version worked to
talk to the camera.

On Wed, Jul 29, 2015 at 12:40 AM, Hannes Badertscher <
notifications@github.com> wrote:

> Sorry for the delay. Now, from the posted log I assume that you are using
> the Microsoft Windows SDK 7.1, which is recommended by MATLAB. Is this
> correct? This would lead to the following problem: SDK 7.1 includes the
> Visual Studio 2010 compilers, which are quite old by now. The
> BaslerCamDriver however relies on the C++11 standard, which is not
> available in SDK 7.1. Could you install and use Microsoft Visual Studio
> <http://www.visualstudio.com/>? Visual Studio Community is available free
> of charge for non-commercial applications. With that the compilation should
> work fine, as from the error message I don't think this problem is related
> to Boost.
>
> About 32bit / 64bit: I am using a 64bit version of MATLAB and use the
> 64-bit Boost and Pylon libraries. With 32bit MATLAB you will need to use
> the 32bit libraries, so please change according library paths. I am hoping
> to create a more intelligent build script which would detect the paths
> automatically, but this is will take some more time.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/HBadertscher/Matlab_BaslerCamDriver/issues/7#issuecomment-125871116>
> .
>



-- 

Sara Wasserman, PhD
Postdoctoral Fellow - Frye Lab
Howard Hughes Medical Institute
UCLA Department of Integrative Biology and Physiology
http://sarawasserman.virb.com/

<http://www.physci.ucla.edu/research/frye>

**Comment by HBadertscher** [comment] 2015-08-03 06:02
Great to hear. If you have any further problems, questions or ideas for improvement, please let me know.

**Closed by HBadertscher** 2015-08-03 06:02 UTC

**Comment by smwasser** [comment] 2015-08-03 18:32
Hi - I know our lab would love the option to be able to do a live real time
continuous preview to be able to watch an experiment as we run it. Thank
you again for your help and time, it is much appreciated!

On Sun, Aug 2, 2015 at 11:02 PM, Hannes Badertscher <
notifications@github.com> wrote:

> Great to hear. If you have any further problems, questions or ideas for
> improvement, please let me know.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/HBadertscher/Matlab_BaslerCamDriver/issues/7#issuecomment-127133396>
> .
>



-- 

Sara Wasserman, PhD
Postdoctoral Fellow - Frye Lab
Howard Hughes Medical Institute
UCLA Department of Integrative Biology and Physiology
http://sarawasserman.virb.com/

<http://www.physci.ucla.edu/research/frye>

**Comment by jrehak** [comment] 2015-08-20 15:05
Hi,
I posted yesterday on the Mathworks site regarding being unable to successfully run make.m. I realized I needed to add BOOST_ROOT to the Windows environment variables path. After doing this, I installed VS 2015 Community as you recommended, but I still get this error. I followed the steps at this [website](http://kaba.hilvi.org/homepage/blog/vs2015_in_matlab_2015/vs_2015_in_matlab_2015.htm) in order to add VS 2015 to my list of compilers.
I only have limited knowledge in C++ so this is all very confusing to me.
Thanks again!

**Comment by frezd** [comment] 2015-10-13 14:42
Hi,

I had exactly the same issues than jrehak. I added BOOST_ROOT and managed to launch the beginning of make.m.
But now I have the same log report than t4qjXH8N had in the beginning so I guess the issue comes from SDK 7.1 that i'm using right now.
I try to uninstall it and install Visual Studio Community instead but then Matlab told me that I didn't have a proper SDK anymore, as if installing VSC doesn't bring any SDK to Matlab.

Do you by chance have any idea of how I could go over that ?

**Comment by babaz123** [comment] 2015-12-16 16:48
@jrehak 
Did you finally manage to run make.m with VS 2015?

Here is the error I get:

>> make
=> Creating Libraries
Building with 'Microsoft Visual C++ 2015'.
Error using mex
basler_set_get.cpp
C:\Program Files\Basler\pylon 4\pylon\include\pylon/PylonUtilityIncludes.h(44): warning C4081: expected 'string'; found
'user-defined string literal'
C:\Program Files\Basler\pylon 4\pylon\include\pylon/PylonIncludes.h(100): warning C4081: expected 'string'; found 'user-defined
string literal'
C:\Users\Z440\Downloads\Matlab_BaslerCamDriver-master\basler_helper\basler_set_get.cpp(113): warning C4244: 'return': conversion
from 'int64_t' to 'int', possible loss of data
C:\Users\Z440\Downloads\Matlab_BaslerCamDriver-master\basler_helper\basler_set_get.cpp(128): warning C4927: illegal conversion;
more than one user-defined conversion has been implicitly applied
C:\Users\Z440\Downloads\Matlab_BaslerCamDriver-master\basler_helper\basler_set_get.cpp(128): note: while calling the constructor
'std::basic_string<char,std::char_traits<char>,std::allocator<char>>::basic_string(const _Elem *)'
        with
        [
            _Elem=char
        ]
C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE\xstring(822): note: see declaration of
'std::basic_string<char,std::char_traits<char>,std::allocator<char>>::basic_string'
C:\Program Files\Basler\pylon 4\genicam\library\CPP\include\GenApi/IEnumerationT.h(338): error C3688: invalid literal suffix
'FMT_I64'; literal operator or literal operator template 'operator ""FMT_I64' not found
C:\Program Files\Basler\pylon 4\genicam\library\CPP\include\GenApi/IEnumerationT.h(328): note: while compiling class template
member function 'Basler_ImageFormatConverterParams::OutputBitAlignmentEnums
GenApi::CEnumerationTRef<Basler_ImageFormatConverterParams::OutputBitAlignmentEnums>::GetValue(bool,bool)'
C:\Program Files\Basler\pylon 4\genicam\library\CPP\include\GenApi/IEnumerationT.h(347): note: see reference to function
template instantiation 'Basler_ImageFormatConverterParams::OutputBitAlignmentEnums
GenApi::CEnumerationTRef<Basler_ImageFormatConverterParams::OutputBitAlignmentEnums>::GetValue(bool,bool)' being compiled
C:\Program Files\Basler\pylon 4\pylon\include\pylon/_ImageFormatConverterParams.h(259): note: see reference to class template
instantiation 'GenApi::CEnumerationTRef<Basler_ImageFormatConverterParams::OutputBitAlignmentEnums>' being compiled



Error in make (line 56)
            mex(flags{:},libraries{k,3},ipaths,lpaths,libraries{k,2})   % build
 
>> 

@HBadertscher 
Could you please help me compile your driver with VS? (I've never used it before.)

**Comment by Lansbergen** [comment] 2016-02-13 16:51
Hi,

I came a cross the same (and unfortunately many more) error as you did. After some struggling I finally managed to create the mex-files by removing the type `class` in when stated 'enum class ParamType' in line 13 of baslerGetParameter.cpp. It worked just fine for me.

Check out the tutorial I wrote on the topic.

https://github.com/Lansbergen/BaslerCamDriver_Installation_Tutorial_Windows_7.git 

Let me know if it worked

**Comment by smwasser** [comment] 2016-02-14 13:58
Thank you very much for sharing this. We decided to use a USB 2 camera but
I will let you know if we try this in the future!

On Sat, Feb 13, 2016 at 11:51 AM, Lansbergen <notifications@github.com>
wrote:

> Hi,
>
> I came a cross the same (and unfortunately many more) error as you did.
> After some struggling I finally managed to create the mex-files by removing
> the type class in when stated 'enum class ParamType' in line 13 of
> baslerGetParameter.cpp. It worked just fine for me.
>
> Check out the tutorial I wrote on the topic.
>
>
> https://github.com/Lansbergen/BaslerCamDriver_Installation_Tutorial_Windows_7.git
>
> Let me know if it worked
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/HBadertscher/Matlab_BaslerCamDriver/issues/7#issuecomment-183701938>
> .
>



-- 

Sara Wasserman, PhD
Postdoctoral Fellow - Frye Lab
UCLA Department of Integrative Biology and Physiology
Research: http://sarawasserman.virb.com
Outreach: http://www.swirlss.org
<http://www.physci.ucla.edu/research/frye>

**Comment by babaz123** [comment] 2016-02-14 14:03
Hello,

I had finally managed to compile the files (cf https://github.com/HBadertscher/Matlab_BaslerCamDriver/issues/12).

However, I couldn't manage to use this program usefully because of https://github.com/HBadertscher/Matlab_BaslerCamDriver/issues/10

Thanks
